#### This code processes log files and the final output is a merged csv file of all evaluations (for now)

In [1]:
from extract_log_data import process_logs
import pandas as pd

In [2]:
df_prompts = pd.read_csv("data\\prompts.csv", sep="|")
df_prompts.head()

   prompt_id written_by                                        user_prompt
0          1     Pratik  Create a simple web app called Plant Care Trac...
1          2     Pratik  Make a Roommate Chore Wheel that randomly assi...
2          3     Pratik  Build a dashboard to monitor car maintenance h...
3          4     Pratik  Build a simple web app that suggests if tomorr...
4          5     Pratik  Build a currency conversion app that takes an ...

In [3]:
source_loc = "data\\logs"
destination_loc = "data\\processed_logs"

df_merged = process_logs(source_loc, destination_loc)

============================================================
PROCESSING FOLDER: data\logs\0111
============================================================
Found 5 log files in data\logs\0111
Processing: prompt_1.log
2025-07-22 12:51:23
Processing: prompt_2.log
2025-07-22 22:01:22
Processing: prompt_3.log
2025-07-23 11:13:03
Processing: prompt_4.log
2025-07-23 13:59:35
Processing: prompt_5.log
2025-07-23 05:51:04
Summary saved to: data\processed_logs\0111_summary.csv
Processed 5 log files
============================================================
PROCESSING FOLDER: data\logs\1111
============================================================
Found 5 log files in data\logs\1111
Processing: prompt_10.log
2025-07-22 22:42:38
Processing: prompt_6.log
2025-07-22 21:36:30
Processing: prompt_7.log
2025-07-22 22:05:00
Processing: prompt_8.log
2025-07-22 23:43:32
Processing: prompt_9.log
2025-07-22 23:55:11
Summary saved to: data\processed_logs\1111_summary.csv
Processed 5 log files

In [4]:
df_merged = df_merged.sort_values(by=["prompt_id"])
df_merged

,prompt_id,log_file,start_time,end_time,gen_time,build_status,post_build_error,gemini_input_tokens,gemini_output_tokens,gemini_total_tokens,gemini_api_calls,anthropic_input_tokens,anthropic_output_tokens,anthropic_total_tokens,anthropic_api_calls,total_api_calls,config
0,1,prompt_1.log,2025-07-22 12:37:47,2025-07-22 12:51:23,13min 36sec,success,False,28992,1008,30000,6,1138414,48205,1186619,69,75,0111
1,2,prompt_2.log,2025-07-22 21:51:03,2025-07-22 22:01:22,10min 19sec,success,False,27907,1054,28961,6,962959,33413,996372,61,67,0111
2,3,prompt_3.log,2025-07-23 11:00:35,2025-07-23 11:13:03,12min 28sec,success,False,22660,950,23610,6,1251805,37280,1289085,109,115,0111
3,4,prompt_4.log,2025-07-23 13:51:44,2025-07-23 13:59:35,7min 51sec,success,False,22832,1022,23854,6,403567,21777,425344,45,51,0111
4,5,prompt_5.log,2025-07-23 05:41:25,2025-07-23 05:51:04,9min 39sec,success,False,19322,1043,20365,6,513263,23001,536264,66,72,0111
6,6,prompt_6.log,2025-07-22 21:22:25,2025-07-22 21:36:30,14min 05sec,success,False,21776,3013,24789,6,1119362,32300,1151662,69,75,1111
7,7,prompt_7.log,2025-07-22 21:48:44,2025-07-22 22:05:00,16min 16sec,success,False,28834,866,29700,6,2010930,39817,2050747,88,94,1111
8,8,prompt_8.log,2025-07-22 23:35:38,2025-07-22 23:43:32,7min 54sec,success,False,21268,801,22069,6,396339,18814,415153,40,46,1111
9,9,prompt_9.log,2025-07-22 23:48:41,2025-07-22 23:55:11,6min 30sec,success,False,17134,813,17947,6,152306,16254,168560,28,34,1111
5,10,prompt_10.log,2025-07-22 22:35:05,2025-07-22 22:42:38,7min 33sec,success,False,19960,988,20948,6,321914,15771,337685,47,53,1111

In [5]:
col_keep = ["prompt_id", "user_prompt"]
df_final = pd.merge(df_merged, df_prompts[col_keep], on="prompt_id", how="left")
df_final.sort_values(by="prompt_id", inplace=True)
df_final.reset_index(inplace=True, drop=True)
df_final

,prompt_id,log_file,start_time,end_time,gen_time,build_status,post_build_error,gemini_input_tokens,gemini_output_tokens,gemini_total_tokens,gemini_api_calls,anthropic_input_tokens,anthropic_output_tokens,anthropic_total_tokens,anthropic_api_calls,total_api_calls,config,user_prompt
0,1,prompt_1.log,2025-07-22 12:37:47,2025-07-22 12:51:23,13min 36sec,success,False,28992,1008,30000,6,1138414,48205,1186619,69,75,0111,Create a simple web app called Plant Care Trac...
1,2,prompt_2.log,2025-07-22 21:51:03,2025-07-22 22:01:22,10min 19sec,success,False,27907,1054,28961,6,962959,33413,996372,61,67,0111,Make a Roommate Chore Wheel that randomly assi...
2,3,prompt_3.log,2025-07-23 11:00:35,2025-07-23 11:13:03,12min 28sec,success,False,22660,950,23610,6,1251805,37280,1289085,109,115,0111,Build a dashboard to monitor car maintenance h...
3,4,prompt_4.log,2025-07-23 13:51:44,2025-07-23 13:59:35,7min 51sec,success,False,22832,1022,23854,6,403567,21777,425344,45,51,0111,Build a simple web app that suggests if tomorr...
4,5,prompt_5.log,2025-07-23 05:41:25,2025-07-23 05:51:04,9min 39sec,success,False,19322,1043,20365,6,513263,23001,536264,66,72,0111,Build a currency conversion app that takes an ...
5,6,prompt_6.log,2025-07-22 21:22:25,2025-07-22 21:36:30,14min 05sec,success,False,21776,3013,24789,6,1119362,32300,1151662,69,75,1111,Generate a Streamlit app called Movie Watchlis...
6,7,prompt_7.log,2025-07-22 21:48:44,2025-07-22 22:05:00,16min 16sec,success,False,28834,866,29700,6,2010930,39817,2050747,88,94,1111,Build a Classic Snake Game with pygame and sca...
7,8,prompt_8.log,2025-07-22 23:35:38,2025-07-22 23:43:32,7min 54sec,success,False,21268,801,22069,6,396339,18814,415153,40,46,1111,Generate Brick Breaker game using Pygame. Gene...
8,9,prompt_9.log,2025-07-22 23:48:41,2025-07-22 23:55:11,6min 30sec,success,False,17134,813,17947,6,152306,16254,168560,28,34,1111,Generate a Memory Card Matching Game. create a...
9,10,prompt_10.log,2025-07-22 22:35:05,2025-07-22 22:42:38,7min 33sec,success,False,19960,988,20948,6,321914,15771,337685,47,53,1111,Write a Flask app called\u202fJoke Collector\u...

In [6]:
df_final.to_csv("data\\evaluations.csv", index=False, sep="|")